-- apps/server/src/db/migrations/0007_task_workflow_state.sql
--
-- Workflow State Machine foundation for D1 (Kanban columns + transition graph).
--
-- Design notes:
-- - workflow_columns: per-project Kanban columns, ordered by position.
--   maps_to_status bridges the Kanban column to the existing task_status enum
--   so pre-D1 logic continues to work unchanged.
-- - workflow_transitions: directed edge list encoding allowed moves between
--   columns within a project (implicitly scoped because both FK columns cascade
--   from workflow_columns, which cascade from projects).
-- - tasks.workflow_column_id is nullable: pre-D1 tasks have no column assigned
--   and the service layer treats NULL as "no workflow placement yet".
-- - IDs are generated by the service layer (uuidv7), not by Postgres, consistent
--   with the rest of the codebase.

-- Extend event_kind enum with the new workflow transition event.
-- IF NOT EXISTS makes this replay-safe.
ALTER TYPE event_kind ADD VALUE IF NOT EXISTS 'workflow_transitioned';

-- Per-project Kanban columns. IDs are generated by the service layer (uuidv7),
-- not by Postgres, consistent with the rest of the codebase.
CREATE TABLE IF NOT EXISTS workflow_columns (
  id             uuid PRIMARY KEY,
  project_id     uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  name           text NOT NULL,
  position       integer NOT NULL,
  maps_to_status task_status NOT NULL,
  is_default     boolean NOT NULL DEFAULT false,
  created_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS workflow_columns_project_idx ON workflow_columns(project_id);

-- Directed allowed-transition graph between columns (per project, implicitly,
-- because both column FKs cascade from the same project).
CREATE TABLE IF NOT EXISTS workflow_transitions (
  from_column_id  uuid NOT NULL REFERENCES workflow_columns(id) ON DELETE CASCADE,
  to_column_id    uuid NOT NULL REFERENCES workflow_columns(id) ON DELETE CASCADE,
  PRIMARY KEY (from_column_id, to_column_id)
);

-- Nullable FK: pre-D1 tasks have no column assignment.
-- ON DELETE SET NULL ensures deleting a workflow column does not block on FK violation.
ALTER TABLE tasks ADD COLUMN workflow_column_id uuid REFERENCES workflow_columns(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS tasks_workflow_column_idx ON tasks(workflow_column_id);
