#!/bin/sh
# Sprino bootstrap — generate a working .env for self-host.
#
# Idempotent: re-running with an existing .env is a no-op unless --force
# is passed. Writes a fresh .env with random tokens and stream secret so
# nothing ships with the dev defaults committed in .env.example.
#
# Requires: openssl (for random secrets and IDs). Python is optional and
# only used for UUIDv7 if available; otherwise we fall back to a v4-style
# random ID, which Postgres accepts since the column is just `uuid`.
#
# Usage:
#   sh bootstrap.sh                    # generate .env if missing
#   sh bootstrap.sh --force            # overwrite existing .env
#   ADMIN_NAME="Alice" sh bootstrap.sh # customize the admin display name

set -eu

# ---------- arg parsing ----------
FORCE=0
for arg in "$@"; do
    case "$arg" in
        --force|-f) FORCE=1 ;;
        --help|-h)
            sed -n '2,15p' "$0" | sed 's/^# \{0,1\}//'
            exit 0
            ;;
        *)
            echo "bootstrap.sh: unknown argument: $arg" >&2
            exit 2
            ;;
    esac
done

# ---------- prereq check ----------
if ! command -v openssl >/dev/null 2>&1; then
    echo "bootstrap.sh: openssl is required (for random tokens)." >&2
    exit 1
fi

# ---------- locate repo root ----------
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
cd "$SCRIPT_DIR"

ENV_FILE=".env"
if [ -f "$ENV_FILE" ] && [ "$FORCE" -ne 1 ]; then
    echo "bootstrap.sh: $ENV_FILE already exists. Use --force to overwrite."
    echo "Existing values were left untouched. To regenerate, run:"
    echo "    sh bootstrap.sh --force"
    exit 0
fi

# ---------- helpers ----------
gen_secret() {
    # 32 bytes hex = 64 chars, well above the 32-char floor enforced
    # by the SSE secret loader.
    openssl rand -hex 32
}

gen_token() {
    # 24 bytes base64 = 32 url-safe chars. Tokens go in Authorization:
    # Bearer headers, so we keep them ASCII-safe.
    openssl rand -base64 24 | tr -d '=+/' | cut -c1-32
}

gen_uuid() {
    # Prefer Python's uuid.uuid4 for a syntactically-valid UUID. Postgres
    # `uuid` accepts any v1-v8; we don't need the temporal ordering of v7
    # for these one-off seed rows.
    if command -v python3 >/dev/null 2>&1; then
        python3 -c 'import uuid; print(uuid.uuid4())'
    else
        # Fallback: 16 random bytes formatted as a UUID with the v4 + RFC
        # 4122 variant bits. POSIX-portable.
        hex=$(openssl rand -hex 16)
        # set version (bits 12-15 of time_hi_and_version) to 4
        v=$(printf '%s' "$hex" | cut -c13-16 | tr 'a-f' 'A-F')
        v=$(printf '4%s' "$(printf '%s' "$v" | cut -c2-4)")
        # set variant (bits 6-7 of clock_seq_hi_and_reserved) to 10xx
        c=$(printf '%s' "$hex" | cut -c17-20)
        c1=$(printf '%s' "$c" | cut -c1)
        case "$c1" in
            [0-3]) c1=8 ;; [4-7]) c1=9 ;; [8-9aAbB]) c1=a ;; *) c1=b ;;
        esac
        c=$(printf '%s%s' "$c1" "$(printf '%s' "$c" | cut -c2-4)")
        printf '%s-%s-%s-%s-%s\n' \
            "$(printf '%s' "$hex" | cut -c1-8)" \
            "$(printf '%s' "$hex" | cut -c9-12)" \
            "$v" \
            "$c" \
            "$(printf '%s' "$hex" | cut -c21-32)"
    fi
}

# ---------- gather inputs ----------
ADMIN_NAME=${ADMIN_NAME:-Admin}
PROJECT_SLUG=${PROJECT_SLUG:-sprino}
PROJECT_NAME=${PROJECT_NAME:-Sprino}

ADMIN_ACTOR_ID=$(gen_uuid)
ADMIN_TOKEN=$(gen_token)
PROJECT_ID=$(gen_uuid)
STREAM_SECRET=$(gen_secret)

# ---------- write .env ----------
# Build SPRINO_ACTORS_JSON via python (json escaping is harder than it
# looks in pure shell when display names can contain spaces or quotes).
if command -v python3 >/dev/null 2>&1; then
    ACTORS_JSON=$(ADMIN_ACTOR_ID="$ADMIN_ACTOR_ID" ADMIN_TOKEN="$ADMIN_TOKEN" ADMIN_NAME="$ADMIN_NAME" \
        python3 -c '
import json, os
print(json.dumps([{
    "id": os.environ["ADMIN_ACTOR_ID"],
    "kind": "human",
    "display_name": os.environ["ADMIN_NAME"],
    "token": os.environ["ADMIN_TOKEN"],
    "agent_runtime": None,
}]))')
else
    # Minimal manual JSON: ADMIN_NAME is forced to ASCII-safe in the
    # check below.
    case "$ADMIN_NAME" in
        *'"'*|*\\*)
            echo "bootstrap.sh: ADMIN_NAME contains characters that would" >&2
            echo "  require JSON escaping; install python3 or use a simpler name." >&2
            exit 1 ;;
    esac
    ACTORS_JSON=$(printf '[{"id":"%s","kind":"human","display_name":"%s","token":"%s","agent_runtime":null}]' \
        "$ADMIN_ACTOR_ID" "$ADMIN_NAME" "$ADMIN_TOKEN")
fi

cat > "$ENV_FILE" <<EOF
# Sprino — generated by bootstrap.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Re-run with --force to regenerate. Tokens below are one-time secrets;
# treat .env like a private key.

# ---------- Database ----------
# Inside Docker Compose, the server reaches Postgres via the service name.
DATABASE_URL=postgres://sprino:sprino@postgres:5432/sprino_dev

# ---------- Auth ----------
SPRINO_ACTORS_JSON='${ACTORS_JSON}'

# ---------- Realtime (SSE) ----------
SPRINO_STREAM_SECRET=${STREAM_SECRET}

# ---------- Project bootstrap ----------
SPRINO_DEFAULT_PROJECT_ID=${PROJECT_ID}
SPRINO_DEFAULT_PROJECT_SLUG=${PROJECT_SLUG}
SPRINO_DEFAULT_PROJECT_DISPLAY_NAME=${PROJECT_NAME}

# ---------- Server ----------
PORT=3001
NODE_ENV=production
LOG_LEVEL=info
EOF

chmod 600 "$ENV_FILE"

# ---------- summary ----------
cat <<EOF

✓ Wrote $ENV_FILE (mode 600)

Next:
    docker compose --profile full up -d
    open http://localhost:3000

Sign in with:
    Name:  ${ADMIN_NAME}
    Token: ${ADMIN_TOKEN}

The token is also stored in $ENV_FILE under SPRINO_ACTORS_JSON.
Keep that file out of version control — it's already in .gitignore.

EOF
